"use strict";
const assert=require('assert'),fs=require('fs'),path=require('path'),AdmZip=require('adm-zip');
const {GoldenCompiler,parse,els,read,relationships,target}=require('../server/golden-native/package');
const {bindChart}=require('../server/golden-native/charts');
const source=path.resolve('docs/golden/golden.pptx');
if(!fs.existsSync(source)){console.log('golden-native integration skipped: local GoldenPPTX is not installed');process.exit(0);}
const g=new GoldenCompiler(source);assert.equal(g.catalog.slides.length,32);
const experimentalFill=(id,plan)=>g.fill(id,{...plan,experimental:true});
const chartSlide=g.catalog.slides.find(s=>s.charts.length);const id=chartSlide.id;
const texts=Object.fromEntries(chartSlide.slots.map(s=>[s.id,'']));
texts[chartSlide.slots.find(s=>s.role==='title').id]='別データで再計算したグラフ';
const data={categories:['1月','2月','3月','4月','5月','6月'],series:[{name:'新系列A',values:[100,110,108,120,130,140]},{name:'新系列B',values:[90,96,101,99,107,115]}],domain:{min:80,max:150}};
assert.throws(()=>g.fill(id,{texts,charts:[data]}),/Semantic geometry binding/);
assert.throws(()=>experimentalFill(id,{texts}),/Every native chart/);
assert.throws(()=>experimentalFill(id,{texts:{p0:'省略'},charts:[data]}),/Missing text slots/);
assert.throws(()=>experimentalFill(id,{texts:{...texts,p999:'wrong'},charts:[data]}),/Unknown text slot/);
assert.throws(()=>experimentalFill(id,{texts:{...texts,p0:'超'.repeat(5000)},charts:[data]}),/exceeds capacity/);
assert.throws(()=>experimentalFill(id,{texts,charts:[{...data,series:[{name:'bad',values:[1,2]}]}]}),/one finite value/);
const buf=experimentalFill(id,{texts,charts:[data]}),zip=new AdmZip(buf),chart=chartSlide.charts[0],cd=parse(read(zip,chart.part));
const series=els(cd,'c','ser');assert.equal(series.length,2);
assert.deepEqual(els(els(series[0],'c','cat')[0],'c','v').map(v=>v.textContent),data.categories);
assert.deepEqual(els(els(series[1],'c','val')[0],'c','v').map(v=>Number(v.textContent)),data.series[1].values);
const workbookRel=relationships(zip,chart.part).find(r=>r.getAttribute('Type').endsWith('/package'));
const wb=new AdmZip(zip.getEntry(target(chart.part,workbookRel.getAttribute('Target'))).getData());
const sheet=read(wb,'xl/worksheets/sheet1.xml');assert(sheet.includes('新系列A')&&sheet.includes('<v>140</v>'));
assert(!sheet.includes('X 社'));
assert(read(zip,chartSlide.part).includes('別データで再計算したグラフ'));
assert(!read(zip,chartSlide.part).includes('FY25'));
assert.equal(els(parse(read(zip,'ppt/presentation.xml')),'p','sldId').length,1);
const out=path.resolve('debug/golden-native');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'changed-chart.pptx'),buf);
console.log('golden-native: package closure, required slots, capacity, native cache/workbook binding verified');
