"use strict";
// Independently authored reference scenes. Never import public/layout here.
// These coordinates are design decisions, not snapshots of the system under test.
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const cases = [];
const W=960,H=540, ink='#252525', gray='#666666', pale='#EEEEEE';
let scene;
function text(t,x,y,w,h,fs=22,opt={}) {
  const boldRanges=[]; let out='', start=0, bold=false;
  for(let i=0;i<t.length;i++) {if(t.slice(i,i+2)==='**'){if(bold)boldRanges.push([start,out.length-start]);else start=out.length;bold=!bold;i++;}else out+=t[i];}
  scene.prims.push({kind:'rect',shape:'rect',x,y,w,h,text:out,fontSize:fs,fontName:'Yu Gothic',color:ink,pad:0,wrap:true,align:'left',valign:'middle',autofit:'none',boldRanges,...opt});
}
function box(x,y,w,h,fill=pale,shape='rect') {scene.prims.push({kind:'rect',shape,x,y,w,h,fill,text:''});}
function line(x1,y1,x2,y2,color='#BBBBBB',weight=1) {scene.prims.push({kind:'line',x1,y1,x2,y2,color,weight});}
function icon(name,x,y,size=88) {scene.prims.push({kind:'image',name,x,y,w:size,h:size,color:ink});}
function begin(id,title,lead) {scene={version:1,width:W,height:H,prims:[]};text(title,40,27,880,49,30,{bold:true,role:'title'});if(lead)text(lead,40,86,880,38,18,{role:'lead'});text('架空の評価用データ',40,509,800,18,10,{color:gray,role:'footnote'});}
function add(id,split,input,spec,required,reason,checks,draw) {
  begin(id,spec.title,spec.lead);draw();
  cases.push({id,split,input,required,design:{reason,checks,oneMainVisual:true},expected:spec,golden:scene});
}
const one=(title,lead,body)=>({panelCount:1,title,lead,footnote:'架空の評価用データ',body});
function processDraw(steps){const n=steps.length,g=16,w=(880-g*(n-1))/n;steps.forEach((s,i)=>{const x=40+i*(w+g);box(x,178,w,52,pale,'homePlate');text(`${String(i+1).padStart(2,'0')}  ${s.head}`,x+6,178,w-30,52,23,{bold:true,align:'center'});icon(s.icon,x+(w-88)/2,262);text(s.text,x+12,374,w-24,60,21,{align:'center'});});}
const steps=[{head:'調査',text:'現状と課題を整理する',icon:'search'},{head:'設計',text:'対応方針と担当を決める',icon:'pencil'},{head:'実行',text:'施策を実行し効果を測る',icon:'rocket'}];
add('process-short','dev','調査、設計、実行の順に進む。調査では現状と課題を整理し、設計では対応方針と担当を決める。実行では施策を実行し効果を測る。',one('調査から実行までを三つの工程で進める','各工程の成果を確認してから次の工程へ進む',{type:'sequence',steps}),['調査','設計','実行','現状','課題','担当','効果'],'短文を矢羽根と意味のあるピクトグラムの一組で示す。下に要約帯を重ねない。',{family:'sequence',icons:3,horizontal:true,minBodyFont:18},()=>processDraw(steps));
const longSteps=[{head:'棚卸し',text:'1,200テーブルの依存関係を確認し、移行対象を確定する。'},{head:'参照系移行',text:'38本のBIを移行する。稼働率99.5%以上、再処理は週3件以下を2週連続で満たすことを確認する。'},{head:'更新系移行',text:'64本のバッチを切り替える。切替リハーサルは2回行う。'},{head:'旧環境停止',text:'運用手順を更新し、年1,800万円のライセンスを解約する。'}];
add('process-long','dev','移行順は棚卸し、参照系移行、更新系移行、旧環境停止。'+longSteps.map(x=>x.text).join(''),one('移行は各工程の確認条件を満たして進める','参照系の安定稼働を確認した後に更新系を切り替える',{type:'sequence',steps:longSteps}),['1,200','38','99.5','3件','2週','64','2回','1,800'],'条件は該当工程と同じ行に置く。長文なので縦方向。',{family:'sequence',icons:0,horizontal:false,minBodyFont:18},()=>longSteps.forEach((s,i)=>{const y=154+i*82;box(40,y,224,68);text(`${String(i+1).padStart(2,'0')}  ${s.head}`,54,y,196,68,21,{bold:true});text(s.text,290,y,624,68,20);if(i<3)line(290,y+78,914,y+78);}));
const panels=[{head:'減少の要因',items:['**商品力の低下**',['商品の陳腐化と品質への不満'],'**営業接点の減少**',['担当者の不足で訪問が減少']]},{head:'優先する打ち手',items:['**商品改善を優先**',['顧客の不満を調査し、品質を改善'],'**営業活動を支援**',['重点顧客への訪問時間を確保']]}];
function panelDraw(ps){const gap=28,w=(880-gap*(ps.length-1))/ps.length;ps.forEach((p,i)=>{const x=40+i*(w+gap);text(p.head,x,151,w,42,25,{bold:true,align:'center'});line(x,200,x+w,200,ink,1.5);let y=ps.length===2?266:256;for(const it of p.items){if(Array.isArray(it)){for(const ch of it){text('– '+ch,x+24,y,w-32,58,19);y+=62;}}else{text(it,x+8,y,w-16,39,22);y+=43;}}});}
add('cause-action','dev','売上は前年比30%減。商品の陳腐化と品質への不満、担当者不足による訪問減少が原因。商品改善を優先し、顧客の不満を調査して品質を改善する。営業支援では重点顧客への訪問時間を確保する。',{panelCount:2,title:'売上減少への対応は商品改善を優先する',lead:'売上は前年比30%減となった',footnote:'架空の評価用データ',panels},['30%','陳腐化','品質','担当者','訪問','顧客'],'対立を等幅二項にする。黒塗りではなく文章と部分太字で優先を伝える。',{family:'panels:2',minBodyFont:18,bold:true},()=>panelDraw(panels));
const ps3=[{head:'品質',items:['**不具合を予防する**',['出荷前検査を標準化']]},{head:'納期',items:['**遅延を早く捉える**',['進捗を毎週確認']]},{head:'コスト',items:['**手戻りを減らす**',['設計レビューを徹底']]}];
add('three-priorities','dev','改善の並列論点は品質、納期、コスト。品質は出荷前検査の標準化で不具合を予防する。納期は毎週の進捗確認で遅延を早く捉える。コストは設計レビューの徹底で手戻りを減らす。',{panelCount:3,title:'改善活動は品質・納期・コストで管理する',lead:'各論点に実行する活動を一つずつ対応させる',footnote:'架空の評価用データ',panels:ps3},['品質','納期','コスト','出荷前検査','毎週','設計レビュー'],'並列の三論点を同じ強さで置く。順序がないため矢印や番号を使わない。',{family:'panels:3',minBodyFont:18},()=>panelDraw(ps3));
const outline=['**対象**：営業部門の申請業務','**変更点**：メール受付を申請フォームに統一','**例外**：緊急案件は電話受付を継続','**開始条件**：全担当者への説明を完了'];
add('single-outline','dev','営業部門の申請業務について。変更点はメール受付を申請フォームに統一すること。ただし緊急案件は電話受付を継続する。開始条件は全担当者への説明完了。',one('申請窓口を統一し、緊急時の電話受付を残す','営業部門の申請業務を対象とする',{type:'cell',items:outline}),['営業','メール','フォーム','緊急','電話','全担当者'],'文書の関係を短い太字ラベルで整理する。一つの文章領域で十分。',{family:'cell',minBodyFont:18,bold:true},()=>outline.forEach((t,i)=>text(t,78,174+i*73,805,52,24)));
const mrows=[{head:'A案',cells:['高い','中程度','短い']},{head:'B案',cells:['中程度','高い','中程度']},{head:'C案',cells:['低い','低い','長い']}];
function matrixDraw(rows,heads){const x=40,y=155,rowW=142,cw=(880-rowW)/heads.length,rh=74;heads.forEach((h,j)=>{box(x+rowW+j*cw,y,cw-3,48);text(h,x+rowW+j*cw,y,cw-3,48,21,{bold:true,align:'center'});});rows.forEach((r,i)=>{const yy=y+56+i*rh;box(x,yy,rowW-8,rh-8);text(r.head,x,yy,rowW-8,rh-8,23,{bold:true,align:'center'});r.cells.forEach((v,j)=>text(v,x+rowW+j*cw,yy,cw,rh-8,22,{align:'center'}));if(i<rows.length-1)line(x+rowW,yy+rh-4,920,yy+rh-4);});}
add('comparison-matrix','dev','3案を共通の観点で比較する。A案は効果が高い、費用は中程度、期間は短い。B案は効果が中程度、費用が高い、期間が中程度。C案は効果が低い、費用が低い、期間が長い。',one('三案の違いを効果・費用・期間で比較する','選定では重視する観点を先に決める',{type:'table',colHeaders:['効果','費用','期間'],rows:mrows}),['A案','B案','C案','効果','費用','期間','短い','長い'],'共通の観点で比較するため一枚のマトリクス。パネル見出しで包まない。',{family:'table',minBodyFont:18},()=>matrixDraw(mrows,['効果','費用','期間']));
const drows=Array.from({length:8},(_,i)=>({head:`案件${String.fromCharCode(65+i)}`,cells:[['営業','開発','運用','企画'][i%4],`${(i+2)*10}万円`,['対応中','完了'][i%2]]}));
function denseDraw(rows){const data=[['案件','担当','費用','状態'],...rows.map(r=>[r.head,...r.cells])];scene.prims.push({kind:'table',x:40,y:157,w:880,h:306,colWidths:[200,220,240,220],rowHeights:data.map(()=>34),cells:data.map((r,i)=>r.map(t=>({text:t,fontSize:18,bold:i===0,fill:i===0?pale:null,color:ink,align:'left'})))});}
add('dense-table','dev','案件一覧を表にする。'+drows.map(r=>`${r.head}：担当${r.cells[0]}、費用${r.cells[1]}、${r.cells[2]}。`).join(''),one('八案件の担当・費用・状態を一覧にする','担当と進捗を同じ行で確認できるようにする',{type:'ntable',colHeaders:['担当','費用','状態'],rows:drows}),drows.flatMap(r=>[r.head,r.cells[1]]),'多項目はネイティブTable。個々のテキストボックスを大量に作らない。',{family:'ntable',nativeTable:true,minBodyFont:16},()=>denseDraw(drows));
const gantt={type:'gantt',groups:[{text:'2027年 上期',span:6}],periods:['4月','5月','6月','7月','8月','9月'],tasks:[{label:'要件整理',start:0,end:1},{label:'設計',start:1,end:2},{label:'開発',start:2,end:4},{label:'検証',start:4,end:5}]};
add('gantt','dev','2027年4月から9月までの計画。要件整理は4〜5月、設計は5〜6月、開発は6〜8月、検証は8〜9月。',one('要件整理から検証までを上期に進める','工程を一部並行させ、9月までに検証を終える',gantt),['2027','4月','5月','6月','7月','8月','9月','要件整理','開発','検証'],'工程と時間の関係だけを描く。下に体制や結論の箱を足さない。',{family:'gantt',minBodyFont:18},()=>{text('2027年 上期',216,144,704,32,21,{bold:true,align:'center'});gantt.periods.forEach((m,i)=>text(m,216+i*117.3,181,117,35,19,{align:'center'}));line(40,221,920,221,ink,1.5);gantt.tasks.forEach((t,i)=>{const y=242+i*55;text(t.label,40,y,165,36,21);box(216+t.start*117.3,y+2,(t.end-t.start+1)*117.3-12,32,'#B8B8B8','homePlate');});});
const bars=[{label:'国内',value:120},{label:'北米',value:90},{label:'欧州',value:60},{label:'アジア',value:45}];
function barsDraw(items,unit){text(`単位：${unit}`,742,143,178,25,16,{align:'right',color:gray});const max=Math.max(...items.map(x=>x.value));items.forEach((a,i)=>{const y=189+i*68;text(a.label,40,y,130,37,21);box(185,y+3,625*a.value/max,31,'#777777');text(String(a.value),185+625*a.value/max+12,y,80,37,22,{bold:true});});}
add('bar-comparison','dev','地域別売上を比較する。国内120億円、北米90億円、欧州60億円、アジア45億円。',one('地域別売上は国内が最も大きい','国内の売上は120億円となった',{type:'bars',unit:'億円',items:bars}),['国内','120','北米','90','欧州','60','アジア','45','億円'],'値の大小を同じ起点の棒で比較する。全て同色にして長さで伝える。',{family:'bars',minBodyFont:18},()=>barsDraw(bars,'億円'));
const trend={type:'line',unit:'件',labels:['4月','5月','6月','7月','8月'],series:[{label:'申請件数',values:[40,55,50,70,80]}]};
function trendDraw(t){const pts=t.series[0].values;const max=Math.ceil(Math.max(...pts)/20)*20;[0,max/2,max].forEach(v=>{const y=446-v/max*244;line(112,y,878,y,'#DDDDDD');text(String(v),45,y-14,52,28,16,{align:'right',color:gray});});text(`単位：${t.unit}`,42,148,120,28,16,{color:gray});pts.forEach((v,i)=>{const x=130+i*174,y=446-v/max*244;if(i)line(x-174,446-pts[i-1]/max*244,x,y,ink,2);box(x-4,y-4,8,8,ink,'ellipse');text(String(v),x-34,y-36,68,28,21,{bold:true,align:'center'});text(t.labels[i],x-42,460,84,30,19,{align:'center'});});}
add('line-trend','dev','申請件数の月次推移。4月40件、5月55件、6月50件、7月70件、8月80件。',one('申請件数は6月の減少後に増加した','8月は80件で、4月の40件から倍増した',trend),['4月','40','5月','55','6月','50','7月','70','8月','80'],'時系列は一本の折れ線。点の値と月を近接させる。',{family:'line',minBodyFont:16},()=>trendDraw(trend));
const org={type:'org',root:{label:'責任者',sub:'全体判断',children:[{label:'企画',sub:'要件整理'},{label:'開発',sub:'実装'},{label:'運用',sub:'受入・監視'}]}};
add('organization','dev','責任者が全体判断を担う。責任者の直下に企画、開発、運用を置く。企画は要件整理、開発は実装、運用は受入と監視を担当する。',one('責任者の下に企画・開発・運用を置く','各チームの役割を明確にする',org),['責任者','全体判断','企画','要件整理','開発','実装','運用','受入','監視'],'線は報告関係だけを表す。根の箱を黒くして優先に見せない。',{family:'org',minBodyFont:18},()=>{line(480,236,480,284,gray,1.5);line(180,284,780,284,gray,1.5);[180,480,780].forEach(x=>line(x,284,x,332,gray,1.5));box(350,157,260,80);text('責任者',350,166,260,33,24,{bold:true,align:'center'});text('全体判断',350,203,260,25,19,{align:'center'});org.root.children.forEach((c,i)=>{const x=50+i*300;box(x,332,260,100);text(c.label,x,347,260,33,24,{bold:true,align:'center'});text(c.sub,x,388,260,30,20,{align:'center'});});});
const layers=[{head:'方針',text:'経営会議が重点領域を決める'},{head:'計画',text:'部門が施策と担当を定める'},{head:'実行',text:'現場が施策を進め、結果を報告する'}];
add('pyramid','dev','上から方針、計画、実行の3層。方針では経営会議が重点領域を決める。計画では部門が施策と担当を定める。実行では現場が施策を進め、結果を報告する。ピラミッドと同じ層の右側に説明を置く。',one('方針を計画に落とし、現場で実行する','各層の役割を対応させる',{type:'pyramid',layers}),['方針','経営会議','計画','部門','担当','実行','現場','結果'],'左の階層形状と右の説明を同じ高さで対応づける。独立した二つの図にしない。',{family:'pyramid',minBodyFont:18},()=>{layers.forEach((l,i)=>{const y=159+i*104;const widths=[150,260,370];box(260-widths[i]/2,y,widths[i],92,['#DDDDDD','#BBBBBB','#999999'][i],i===0?'triangle':'trapezoid');text(l.head,130,y+(i===0?36:18),260,48,23,{bold:true,align:'center'});line(450,y+50,488,y+50);text(l.text,510,y+12,400,76,22);});});
// Holdouts have distinct inputs; neither examples nor prompt tuning may read these inputs.
const hs=[{head:'受付',text:'申請内容を確認する',icon:'clipboard-check'},{head:'審査',text:'基準への適合を調べる',icon:'search'},{head:'承認',text:'責任者が可否を決める',icon:'user-check'},{head:'通知',text:'申請者へ結果を伝える',icon:'mail'}];
add('holdout-process-four','holdout','受付で申請内容を確認し、審査で基準への適合を調べる。その後、承認で責任者が可否を決め、通知で申請者へ結果を伝える。',one('申請は受付から通知まで四工程で扱う','可否の判断を終えてから申請者へ結果を伝える',{type:'sequence',steps:hs}),['受付','申請内容','審査','基準','承認','責任者','通知','申請者'],'未使用の四工程でも方向と図像を同じ原則で表す。',{family:'sequence',icons:4,horizontal:true,minBodyFont:18},()=>processDraw(hs));
const hp=[{head:'現状',items:['**窓口が分散**',['問い合わせ先が分かりにくい'],'**履歴が未共有**',['同じ説明を繰り返している']]},{head:'変更後',items:['**窓口を一本化**',['共通フォームで受け付ける'],'**履歴を共有**',['対応記録を検索できるようにする']]}];
add('holdout-before-after','holdout','現状は窓口が分散して問い合わせ先が分かりにくく、履歴が未共有なので同じ説明を繰り返す。変更後は共通フォームに窓口を一本化し、対応記録を共有して検索できるようにする。',{panelCount:2,title:'窓口と対応履歴を共通化する',lead:'問い合わせ先の迷いと説明の繰り返しを減らす',footnote:'架空の評価用データ',panels:hp},['窓口','分散','履歴','共有','共通フォーム','検索'],'原因・打ち手以外の対立でも等価な二パネルを保つ。',{family:'panels:2',minBodyFont:18,bold:true},()=>panelDraw(hp));
const hb=[{label:'製造',value:72},{label:'物流',value:48},{label:'販売',value:36},{label:'管理',value:24}];
add('holdout-bars','holdout','部門別の工数は製造72時間、物流48時間、販売36時間、管理24時間。',one('部門別工数は製造が最も大きい','製造に72時間を要している',{type:'bars',unit:'時間',items:hb}),hb.flatMap(x=>[x.label,String(x.value)]),'単位と題材が変わっても棒の尺度を保持する。',{family:'bars',minBodyFont:18},()=>barsDraw(hb,'時間'));
const hm=[{head:'東拠点',cells:['12人','24席','6室']},{head:'西拠点',cells:['18人','30席','8室']},{head:'南拠点',cells:['9人','15席','3室']}];
add('holdout-matrix','holdout','拠点別の人員、座席、会議室を比較する。東拠点は12人、24席、6室。西拠点は18人、30席、8室。南拠点は9人、15席、3室。',one('拠点別の人員と設備を一覧で比較する','西拠点は人員・座席・会議室がいずれも最多',{type:'table',colHeaders:['人員','座席','会議室'],rows:hm}),hm.flatMap(r=>[r.head,...r.cells]),'定性比較で学んだ行列配置を数値と単位にも適用する。',{family:'table',minBodyFont:18},()=>matrixDraw(hm,['人員','座席','会議室']));
const out=path.resolve(__dirname,'../../test/golden/cases.json');
fs.writeFileSync(out,JSON.stringify({version:1,authoredBy:'Astra in this task',status:'agent-reviewed; awaiting user review',synthetic:true,coordinateSystem:'960x540 pt',cases},null,2)+'\n');
fs.writeFileSync(path.join(path.dirname(out),'manifest.json'),JSON.stringify({version:1,sha256:crypto.createHash('sha256').update(fs.readFileSync(out)).digest('hex'),count:cases.length,dev:cases.filter(c=>c.split==='dev').length,holdout:cases.filter(c=>c.split==='holdout').length},null,2)+'\n');
console.log('Authored',cases.length,'independent golden scenes');
